local options = {
    ensure_installed = {
        "bash",
        "c",
        -- "cmake",
        "cpp",
        "fish",
        -- "go",
        -- "gomod",
        -- "gosum",
        -- "gotmpl",
        -- "gowork",
        -- "haskell",
        "lua",
        "luadoc",
        -- "make",
        "markdown",
        -- "odin",
        "printf",
        "python",
        "toml",
        "vim",
        "vimdoc",
        "yaml",
        "typescript",
        "javascript",
        "json",
        "jsonc",
        "html",
        "css",
        "scss",
        "rust",
        "dockerfile",
        "sql",
        "bash",
        "regex",
        "diff",
        "git_rebase",
        "gitcommit",
    },

    highlight = {
        enable = true,
        use_languagetree = true,
    },

    indent = { enable = true },
}

require("nvim-treesitter.configs").setup(options)
